@baseUrl = http://localhost:8080/odata/v4/odata/v4

### Get all employees
GET {{baseUrl}}/Employees
Accept: application/json
Authorization: Basic admin:

###

### Get one employees
GET {{baseUrl}}/Employees(e5555555-e555-4555-8555-e55555555555)
Accept: application/json
Authorization: Basic admin:

###

### Get user login information
GET {{baseUrl}}/me()
Accept: application/json
Authorization: Basic viewer:

### Calculate Salary
GET {{baseUrl}}/calculateSalary?role=55555555-5555-5555-5555-555555555555&hireDate=2022-05-17
Accept: application/json
Authorization: Basic viewer:

###

### Create new employee
POST {{baseUrl}}/Employees
Content-Type: application/json
Authorization: Basic admin:

{
  "firstName": "Lavy",
  "lastName": "Nguyen",
  "dateOfBirth": "1999-07-20",
  "email": "lavy@gmail.com",
  "gender": "female",
  "hireDate": "2016-07-11",
  "department_ID": "aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1",
  "role_ID": "55555555-5555-5555-5555-555555555555",
  "salary": 88000
}

###

### Update employee
PATCH {{baseUrl}}/Employees(e5555555-e555-4555-8555-e55555555555)
Content-Type: application/json
Authorization: Basic admin:

{
  "firstName": "hahaha",
  "lastName": "Smith",
  "email": "alice.smith@example.com",
  "hireDate": "2022-05-18",
  "role_ID": "22222222-2222-2222-2222-222222222222",
  "salary": 73000
}

###

### Delete employee
DELETE {{baseUrl}}/Employees(e5555555-e555-4555-8555-e55555555555)
Authorization: Basic admin:

##############################################

### Get all Department
GET {{baseUrl}}/Departments
Accept: application/json
Authorization: Basic admin:

##############################################

### Get all Roles
GET {{baseUrl}}/Roles
Accept: application/json
Authorization: Basic viewer:
